name: ci test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: get code
      uses: actions/checkout@v4

    - name: run tests
      run: mvn test